import { Product } from "./types";

/**
 * Sample catalog data. Swap this out for data coming from your CMS,
 * database, or API — the components below only depend on the Product shape.
 */
export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "wb-emulsion-white",
    name: "Premium Acrylic Emulsion – White",
    category: "water-based",
    image: "/images/products/acrylic-emulsion-white-1.jpg",
    gallery: [
      "/images/acrylic-emulsion-white-1.jpg",
      "/images/products/acrylic-emulsion-white-2.jpg",
      "/images/products/acrylic-emulsion-white-3.jpg",
      "/images/products/acrylic-emulsion-white-4.jpg",
      "/images/products/acrylic-emulsion-white-5.jpg",
    ],
    price: 2400,
    discountPercent: 15,
    unit: "per 20L",
    inStock: true,
    shortDescription: "A smooth, washable finish for interior walls and ceilings.",
    description:
      "Our premium acrylic emulsion gives interior walls a smooth, low-sheen finish that resists stains and light scrubbing. Formulated for easy application by brush, roller, or spray, it covers evenly in two coats and dries to a durable, washable surface that holds its color for years.",
    specifications: [
      { label: "Coverage", value: "120–140 sq.ft per litre, per coat" },
      { label: "Drying time", value: "2 hours touch dry, 4 hours recoat" },
      { label: "Finish", value: "Low sheen / matte" },
      { label: "Base", value: "Water" },
      { label: "Recommended coats", value: "2" },
    ],
    bulkPricing: [
      { minQty: 1, pricePerUnit: 2040 },
      { minQty: 5, pricePerUnit: 1950 },
      { minQty: 10, pricePerUnit: 1850 },
    ],
  },
  {
    id: "wb-primer",
    name: "Water Based Wall Primer",
    category: "water-based",
    image: "/images/products/wall-primer-1.jpg",
    gallery: [
      "/images/products/wall-primer-1.jpg",
      "/images/products/wall-primer-2.jpg",
      "/images/products/wall-primer-3.jpg",
      "/images/products/wall-primer-4.jpg",
      "/images/products/wall-primer-5.jpg",
    ],
    price: 950,
    unit: "per 10L",
    inStock: true,
    shortDescription: "Seals porous surfaces and improves topcoat adhesion.",
    description:
      "A water based primer that seals plaster and masonry, evens out surface porosity, and helps your topcoat go on smoother with better coverage. Low odor and quick drying, making it suitable for occupied spaces.",
    specifications: [
      { label: "Coverage", value: "130–150 sq.ft per litre" },
      { label: "Drying time", value: "1 hour touch dry" },
      { label: "Finish", value: "Matte" },
      { label: "Base", value: "Water" },
    ],
    bulkPricing: [
      { minQty: 1, pricePerUnit: 950 },
      { minQty: 6, pricePerUnit: 890 },
    ],
  },
  {
    id: "cb-white-cement",
    name: "Snow White Cement",
    category: "cement-based",
    image: "/images/products/white-cement-1.jpg",
    gallery: [
      "/images/products/white-cement-1.jpg",
      "/images/products/white-cement-2.jpg",
      "/images/products/white-cement-3.jpg",
      "/images/products/white-cement-4.jpg",
      "/images/products/white-cement-5.jpg",
    ],
    price: 480,
    discountPercent: 10,
    unit: "per 40kg bag",
    inStock: true,
    shortDescription: "Fine white cement for wall putty and decorative finishing.",
    description:
      "A high-brightness white cement suited for wall putty, tile grouting, and decorative concrete work. Fine particle size gives a smoother finish and better bonding than ordinary grey cement for finishing applications.",
    specifications: [
      { label: "Bag weight", value: "40kg" },
      { label: "Setting time", value: "30 min initial, 600 min final" },
      { label: "Shelf life", value: "6 months in dry storage" },
    ],
    bulkPricing: [
      { minQty: 1, pricePerUnit: 432 },
      { minQty: 20, pricePerUnit: 405 },
      { minQty: 50, pricePerUnit: 380 },
    ],
  },
  {
    id: "cb-tile-adhesive",
    name: "Cement Based Tile Adhesive",
    category: "cement-based",
    image: "/images/products/tile-adhesive-1.jpg",
    gallery: [
      "/images/products/tile-adhesive-1.jpg",
      "/images/products/tile-adhesive-2.jpg",
      "/images/products/tile-adhesive-3.jpg",
      "/images/products/tile-adhesive-4.jpg",
      "/images/products/tile-adhesive-5.jpg",
    ],
    price: 620,
    unit: "per 25kg bag",
    inStock: false,
    shortDescription: "High-bond adhesive for ceramic and vitrified tiles.",
    description:
      "A polymer-modified cement adhesive designed for fixing ceramic, vitrified, and natural stone tiles on floors and walls. Provides strong bond strength and workable open time for easier tile alignment.",
    specifications: [
      { label: "Bag weight", value: "25kg" },
      { label: "Pot life", value: "3–4 hours" },
      { label: "Open time", value: "20 minutes" },
    ],
  },
  {
    id: "wp-liquid-membrane",
    name: "Liquid Waterproofing Membrane",
    category: "waterproofing",
    image: "/images/products/waterproof-membrane-1.jpg",
    gallery: [
      "/images/products/waterproof-membrane-1.jpg",
      "/images/products/waterproof-membrane-2.jpg",
      "/images/products/waterproof-membrane-3.jpg",
      "/images/products/waterproof-membrane-4.jpg",
      "/images/products/waterproof-membrane-5.jpg",
    ],
    price: 3100,
    discountPercent: 20,
    unit: "per 20L",
    inStock: true,
    shortDescription: "Flexible, seamless membrane for wet areas and terraces.",
    description:
      "A ready-to-use liquid membrane that cures into a flexible, seamless waterproof layer. Ideal for bathrooms, terraces, and planter boxes. Bridges hairline cracks and remains flexible through temperature changes so it won't crack with building movement.",
    specifications: [
      { label: "Coverage", value: "18–20 sq.ft per litre, 2 coats" },
      { label: "Curing time", value: "24 hours between coats" },
      { label: "Elongation", value: "180% at break" },
    ],
    bulkPricing: [
      { minQty: 1, pricePerUnit: 2480 },
      { minQty: 4, pricePerUnit: 2350 },
    ],
  },
  {
    id: "wp-roof-coat",
    name: "Elastomeric Roof Coating",
    category: "waterproofing",
    image: "/images/products/roof-coating-1.jpg",
    gallery: [
      "/images/products/roof-coating-1.jpg",
      "/images/products/roof-coating-2.jpg",
      "/images/products/roof-coating-3.jpg",
      "/images/products/roof-coating-4.jpg",
      "/images/products/roof-coating-5.jpg",
    ],
    price: 2850,
    unit: "per 15L",
    inStock: true,
    shortDescription: "Reflective coating that reduces heat and stops leaks.",
    description:
      "A UV-reflective elastomeric coating for flat and sloped roofs. Reduces surface heat build-up while sealing against water ingress. Stretches and recovers with roof expansion and contraction across seasons.",
    specifications: [
      { label: "Coverage", value: "25–30 sq.ft per litre" },
      { label: "Reflectance", value: "Up to 85% solar reflectance" },
      { label: "Recoat", value: "Every 3–5 years" },
    ],
  },
  {
    id: "ob-enamel-black",
    name: "Synthetic Enamel – Jet Black",
    category: "oil-based",
    image: "/images/products/enamel-black-1.jpg",
    gallery: [
      "/images/products/enamel-black-1.jpg",
      "/images/products/enamel-black-2.jpg",
      "/images/products/enamel-black-3.jpg",
      "/images/products/enamel-black-4.jpg",
      "/images/products/enamel-black-5.jpg",
    ],
    price: 1350,
    discountPercent: 12,
    unit: "per 4L",
    inStock: true,
    shortDescription: "Glossy, hard-wearing enamel for metal and wood trim.",
    description:
      "A high-gloss synthetic enamel that dries to a tough, washable film. Suited for railings, grilles, doors, and furniture. Good flow and leveling for a smooth brush finish with strong color retention outdoors.",
    specifications: [
      { label: "Coverage", value: "60–70 sq.ft per litre" },
      { label: "Drying time", value: "4–6 hours touch dry" },
      { label: "Finish", value: "High gloss" },
      { label: "Base", value: "Oil" },
    ],
    bulkPricing: [
      { minQty: 1, pricePerUnit: 1188 },
      { minQty: 6, pricePerUnit: 1120 },
    ],
  },
  {
    id: "ob-wood-varnish",
    name: "Oil Based Wood Varnish",
    category: "oil-based",
    image: "/images/products/wood-varnish-1.jpg",
    gallery: [
      "/images/products/wood-varnish-1.jpg",
      "/images/products/wood-varnish-2.jpg",
      "/images/products/wood-varnish-3.jpg",
      "/images/products/wood-varnish-4.jpg",
      "/images/products/wood-varnish-5.jpg",
    ],
    price: 1100,
    unit: "per 2L",
    inStock: true,
    shortDescription: "Clear protective finish that enhances natural wood grain.",
    description:
      "A clear oil based varnish that enriches wood grain while protecting against moisture and everyday wear. Suitable for furniture, doors, and window frames, indoors or under cover outdoors.",
    specifications: [
      { label: "Coverage", value: "120–150 sq.ft per litre" },
      { label: "Finish", value: "Gloss / satin available" },
      { label: "Recoat", value: "16–24 hours" },
    ],
  },
  {
    id: "ob-metal-primer",
    name: "Anti-Rust Metal Primer",
    category: "oil-based",
    image: "/images/products/metal-primer-1.jpg",
    gallery: [
      "/images/products/metal-primer-1.jpg",
      "/images/products/metal-primer-2.jpg",
      "/images/products/metal-primer-3.jpg",
      "/images/products/metal-primer-4.jpg",
      "/images/products/metal-primer-5.jpg",
    ],
    price: 890,
    unit: "per 4L",
    inStock: true,
    shortDescription: "Rust-inhibiting primer for ferrous metal surfaces.",
    description:
      "A red-oxide based primer that inhibits corrosion on iron and steel surfaces before top-coating. Forms a strong key for enamel or oil based finishes and extends the life of exposed metalwork.",
    specifications: [
      { label: "Coverage", value: "70–80 sq.ft per litre" },
      { label: "Drying time", value: "3–4 hours" },
      { label: "Recommended topcoat", value: "Synthetic enamel" },
    ],
  },
  {
    id: "ac-roller-set",
    name: "Professional Roller Set (5pc)",
    category: "accessories",
    image: "/images/products/roller-set-1.jpg",
    gallery: [
      "/images/products/roller-set-1.jpg",
      "/images/products/roller-set-2.jpg",
      "/images/products/roller-set-3.jpg",
      "/images/products/roller-set-4.jpg",
      "/images/products/roller-set-5.jpg",
    ],
    price: 550,
    discountPercent: 25,
    unit: "per set",
    inStock: true,
    shortDescription: "5-piece roller kit for smooth walls and ceilings.",
    description:
      "A complete roller kit with two nap rollers, a foam roller for trim, an extension pole, and a paint tray. Suitable for both water and oil based paints on walls and ceilings.",
    specifications: [
      { label: "Pieces", value: "5" },
      { label: "Roller width", value: "9 inch" },
      { label: "Nap length", value: "medium (for smooth to lightly textured walls)" },
    ],
  },
  {
    id: "ac-brush-kit",
    name: "Painter's Brush Kit",
    category: "accessories",
    image: "/images/products/brush-kit-1.jpg",
    gallery: [
      "/images/products/brush-kit-1.jpg",
      "/images/products/brush-kit-2.jpg",
      "/images/products/brush-kit-3.jpg",
      "/images/products/brush-kit-4.jpg",
      "/images/products/brush-kit-5.jpg",
    ],
    price: 380,
    unit: "per kit",
    inStock: true,
    shortDescription: "Assorted brushes for trim, edges, and detail work.",
    description:
      "A set of angled and flat brushes in varying sizes for cutting-in edges, trim work, and detailed touch-ups. Synthetic bristles suitable for both water and oil based paints.",
    specifications: [
      { label: "Pieces", value: "6" },
      { label: "Bristle type", value: "Synthetic" },
    ],
  },
  {
    id: "ac-masking-tape",
    name: "Masking Tape – 48mm",
    category: "accessories",
    image: "/images/products/masking-tape-1.jpg",
    gallery: [
      "/images/products/masking-tape-1.jpg",
      "/images/products/masking-tape-2.jpg",
      "/images/products/masking-tape-3.jpg",
      "/images/products/masking-tape-4.jpg",
      "/images/products/masking-tape-5.jpg",
    ],
    price: 90,
    unit: "per roll",
    inStock: true,
    shortDescription: "Clean-edge masking tape for crisp paint lines.",
    description:
      "A general purpose masking tape that gives crisp, clean paint lines and removes without leaving residue on most surfaces when used within the recommended time window.",
    specifications: [
      { label: "Width", value: "48mm" },
      { label: "Length", value: "20m per roll" },
      { label: "Removal window", value: "Up to 14 days" },
    ],
    bulkPricing: [
      { minQty: 1, pricePerUnit: 90 },
      { minQty: 12, pricePerUnit: 75 },
    ],
  },
];